// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavoriteHost(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddFavoriteHost'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteConnectionHistory(arg1) {
  return window['go']['main']['App']['DeleteConnectionHistory'](arg1);
}

export function DeleteFavoriteHost(arg1) {
  return window['go']['main']['App']['DeleteFavoriteHost'](arg1);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GenerateKey(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateKey'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAuditLogs() {
  return window['go']['main']['App']['GetAuditLogs']();
}

export function GetConnectionHistory() {
  return window['go']['main']['App']['GetConnectionHistory']();
}

export function GetFavoriteHosts() {
  return window['go']['main']['App']['GetFavoriteHosts']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetPrivKeyContent(arg1) {
  return window['go']['main']['App']['GetPrivKeyContent'](arg1);
}

export function GetPubKeyContent(arg1) {
  return window['go']['main']['App']['GetPubKeyContent'](arg1);
}

export function GetSSHConfig() {
  return window['go']['main']['App']['GetSSHConfig']();
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function ImportHostsFromConfig() {
  return window['go']['main']['App']['ImportHostsFromConfig']();
}

export function ListKeys() {
  return window['go']['main']['App']['ListKeys']();
}

export function SaveSSHConfig(arg1) {
  return window['go']['main']['App']['SaveSSHConfig'](arg1);
}

export function SearchConnectionHistory(arg1) {
  return window['go']['main']['App']['SearchConnectionHistory'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateFavoriteHost(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateFavoriteHost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ValidateSSHConfig(arg1) {
  return window['go']['main']['App']['ValidateSSHConfig'](arg1);
}
