// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavoriteHost(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function DeleteConnectionHistory(arg1:number):Promise<Record<string, any>>;

export function DeleteFavoriteHost(arg1:number):Promise<Record<string, any>>;

export function DeleteKey(arg1:string):Promise<Record<string, any>>;

export function ExportConfig(arg1:string):Promise<Record<string, any>>;

export function GenerateKey(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function GetAuditLogs():Promise<Record<string, any>>;

export function GetConnectionHistory():Promise<Record<string, any>>;

export function GetFavoriteHosts():Promise<Record<string, any>>;

export function GetGroups():Promise<Record<string, any>>;

export function GetPrivKeyContent(arg1:string):Promise<Record<string, any>>;

export function GetPubKeyContent(arg1:string):Promise<Record<string, any>>;

export function GetSSHConfig():Promise<Record<string, any>>;

export function ImportConfig(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ImportHostsFromConfig():Promise<Record<string, any>>;

export function ListKeys():Promise<Record<string, any>>;

export function SaveSSHConfig(arg1:string):Promise<Record<string, any>>;

export function SearchConnectionHistory(arg1:string):Promise<Record<string, any>>;

export function TestConnection(arg1:string,arg2:number):Promise<Record<string, any>>;

export function UpdateFavoriteHost(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string):Promise<Record<string, any>>;

export function ValidateSSHConfig(arg1:string):Promise<Record<string, any>>;
